### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by SeeingDragon** [wakatime/gedit-wakatime#13]
I could not find the wakatime.cfg
Operating System: Ubuntu

**Comment by alanhamlett** [comment]
`~/.wakatime.cfg` is the same as `$HOME/.wakatime.cfg` is a hidden file in your user home folder. To see it, you need to run `ls -a` because the filename starts with a dot.

**Comment by SeeingDragon** [comment]
> `~/.wakatime.cfg` is the same as `$HOME/.wakatime.cfg` is a hidden file in your user home folder. To see it, you need to run `ls -a` because the filename starts with a dot.

Thank very much，i have done it。
