### ISSUE TITLE
during setup executing the install.py error

### ISSUE THREAD

**Issue by BannerBomb** [wakatime/gedit-wakatime#4]
When I execute the install.py file, it displays both an error and a successfully installed message.
![image](https://user-images.githubusercontent.com/11788894/49753636-0125c280-fc82-11e8-8f79-e7900b525111.png)

**Comment by tristan957** [comment]
Just install pip through your package manager

**Comment by alanhamlett** [comment]
Fixed with 16ceddb7d65cfbd6d7bdf1500d084b1f8d82b2ae.
