### ISSUE TITLE
AttributeError: Module Pip has no attribute 'main'

### ISSUE THREAD

**Issue by furioness** [wakatime/gedit-wakatime#6]
Here https://stackoverflow.com/questions/49839610/attributeerror-module-pip-has-no-attribute-main says that since old times pip moved 'main' into internals, so in file setup.py:36 needs to change to something like this
`from pip._internal import main`
` main(['install', 'wakatime'])`

**Comment by alanhamlett** [comment]
Fixed now that we're no longer using pip for the install.
