### ISSUE TITLE
Install script internal issues

### ISSUE THREAD

**Issue by mvolfik** [wakatime/gedit-wakatime#8]
Hello, I have a few issues regarding the install script. I understand that this plugin is rather small and can't address complex and rare situations during its installations. But I'll list them anyway:

- Why does it need `sudo`? It doesn't fail without it, and there shouldn't be a reason for it to - we're only copying files into a folder under `~/.local`. If the user decides to use a different directory for plugins and root privileges are required for that, he will most likely know himself that he needs `sudo`

- `pip`, WakaTime CLI installation
  - [`pip` shouldn't be used by importing](https://pip.pypa.io/en/stable/user_guide/#id9). Replace with `subprocess`
  - `wakatime` presence is detected by importing, but always used as `subprocess`. This also broke in my case, as I had WakaTime CLI installed with [`pipx`](https://pipxproject.github.io/pipx/) – in an isolated environment, and only a special `wakatime` executable is placed in `~/.local/bin`. However, it's not available for import, so the install script didn't detect it, and installed it again with `pip`, overwriting the executable.
  - The CLI should probably be updated at some point too,

- Gedit version detection. Currently, there's hardcoded version 3. I found two places where I could get some versions – `gi.__version__` gives me `3.36.0`, `gi._versions["Gedit"]` gives `3.0`. But my Gedit shows `3.36.2`.

**Comment by alanhamlett** [comment]
Fixed in v2.0.1.
