### ISSUE TITLE
Feat: Consider using python3-setuptools instead of install.py

### ISSUE THREAD

**Issue by JPeisach** [wakatime/gedit-wakatime#9]
Hello there,

I'm an Ubuntu/Debian Contributor (sort of). I think packaging this would be cool, and I would LOVE to do it but I have an idea:

For this gedit plugin we're using a self-made install.py script. It may be better to use what most gedit  plugins use, python3-setuptools. While upstream GNOME Gedit plugin repo's aren't made this way, for Debian packaging it would be a) much nicer and b) easier to use. A few examples of this is in Nemo, an alternative to GNOME's Nautilus for Cinnamon's extensions repo, which has lots of python plugins and [each of them have setuptools python files. (example: nemo-compare)](https://github.com/linuxmint/nemo-extensions/blob/master/nemo-compare/setup.py)

With debian pacakging tools such as dh_python3 this makes things a lot easier.

I'll probably open a PR for this but I thought I should open this for discussion first.

**Comment by alanhamlett** [comment]
It makes more sense to use `install.py` now that part of the plugin is in Go.
